version: '3'
services:
    redis:
       image: redis
       ports:
           - "4081:8081"
    mongodb:
        image: mongo
        ports:
           - "27017:27017"
    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
          - "5672:5672"
          - "15672:15672"
    elasticsearch:
        container_name: es-container
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
        environment:
        - xpack.security.enabled=false
        - "discovery.type=single-node"
        ports:
        - 9200:9200
    kibana:
        container_name: kb-container
        image: docker.elastic.co/kibana/kibana:8.6.2
        ports:
        - 5601:5601
        environment:
        - ELASTICSEARCH_HOSTS=http://es-container:9200
        depends_on:
        - elasticsearch
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
        - 8080:8080
        - 50000:50000
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: janekines1234@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
        - 5050:80
    postgres:
        image: postgres:latest
        container_name: postgresdb
        environment:
            POSTGRES_USER: super_admin
            POSTGRES_PASSWORD: admin
            PGDATA: /data/postgres
        volumes:
        - db:/var/lib/postgresql/data
        ports:
        - 5432:5432
volumes:
  db:
    driver: local