version: '3.4'

services:
 danceschoolapi:
   image: danceschoolapi:dev
   environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ASPNETCORE_URLS=https://+:443;http://+:80
     - ASPNETCORE_Kestrel__Certificates__Default__Password=dp2023
     - ASPNETCORE_Kestrel__Certificates__Default__Path=~\.aspnet\https\aspnetapp.pfx
     - ASPNETCORE_HTTPS_PORT=5556
   ports:
     - "5555:80"
     - "5556:443"
   volumes:
     - ~\.aspnet\https:\root\.aspnet\https:ro
     - ~\.microsoft\usersecrets:\root\.microsoft\usersecrets:ro